spring:

  JWT_SECRET_KEY: ${JWT_SECRET_KEY}


  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${DATABASE_NAME}
      auto-index-creation: true

  application:
    name: techhire-core-api
    